### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by CSCSxx** [borisbrodski/redmine_password_encrypter#1]
Hello,
I have just tried the plugin with Redmine version 4.1.2.
Either I'm too stupid or something isn't working right.
In an issue, I type in the description:

PWD-

nothing happens. If I then write a password after it ... nothing happens. If I save the issue, the field is marked accordingly, with the password in clear text. If I click on it, a prompt comes up and asks for a password, but it doesn't exist. The password is also saved unencrypted in the database ...

What am I doing wrong? ;)

**Comment by borisbrodski** [comment]
Thank you for trying my plugin 😃.

Did you typed "PWD-" with one stoke? (Not moving cursor or using backspace or delete)

Which browser do you use?

**Comment by CSCSxx** [comment]
Hi, yes with one stoke
Chrome Version 90.0.443.93 64Bit

**Comment by kma-systo** [comment]
Tried it today too on a fresh 4.2 install, doesn't work for me neither. -> deleted.

**Comment by CSCSxx** [comment]
It also don't work for me -> now using vault
